#!/usr/bin/env python
from os import system, path;
from random import randrange, randint, choice;
from json import load;
from requests import get, post, exceptions;
from socks import setdefaultproxy, PROXY_TYPE_SOCKS5, socksocket;
from socket import socket;
from time import sleep;
from scapy.all import Ether, ARP, srp, sniff;
from multiprocessing import Process;

############################################################################################## Start Variables
help_command = """4n0nym1z3 1.0.0 - (C) 2024
https://github.com/amirkoshkian/4n0nym1z3

Usage: sudo 4n0nym1z3

Options:
    swt : start 4n0nym1z3 with tor
    swp : start 4n0nym1z3 with proxychains
    stop : stop 4n0nym1z3
    status : show status
    ti : auto tor ip changer
    am : activate anti mitm
    n : activate noise traffic generator random
    tiam : run `ti` and `am`
    tiamn : run `ti` and `am` and `n`
    0 : kill apps and clear cache
    1 : log killer
    help : show help
    clear : clear console
    install : install requirements
    exit : exit 4n0nym1z3""";
############################################################################################### End Variables

############################################################################################### Start Section Functions
######################################## Start Section Start Functions
# Start Section Function Start Kill Apps And Clear Cache
def StartKillAppsAndClearCache():
    system("sudo killall -q chrome dropbox skype icedove thunderbird firefox firefox-esr chromium xchat hexchat transmission steam firejail");
    system("sudo bleachbit -l | grep -E '[a-z0-9_\-]+\.[a-z0-9_\-]+' | grep -v system.free_disk_space | grep -v system.memory | grep -v journald.clean | sudo xargs bleachbit -c > /dev/null");
# End Section Function Start Kill Apps And Clear Cache

# Start Section Function Start Ip Changer With Tor
def StartIpChangerWithTor():
    system("sudo iptables-save > /usr/share/4n0nym1z3/data/iptables.txt");
    system("sudo /usr/share/4n0nym1z3/iptables");
    system("sudo cat /etc/tor/torrc > /usr/share/4n0nym1z3/data/torrc.txt");
    system("""sudo cat > /etc/tor/torrc << EOF
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
TransPort 9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
SocksPort 9050
DNSPort 5353
EOF""");
    system("sudo systemctl --system daemon-reload");
    system("sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=1 > /dev/null");
    system("sudo systemctl restart tor");
    system("sudo cat /etc/resolv.conf > /usr/share/4n0nym1z3/data/resolv.txt");
    system("""sudo cat > "/etc/resolv.conf" << EOF
# generated by 4n0nym1z3
nameserver 127.0.0.1
EOF""");
# End Section Function Start Ip Changer With Tor

# Start Section Function Start Ip Changer With Proxy Chains
def StartIpChangerWithProxyChains():
    system("sudo systemctl --system daemon-reload");
    system("sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=1 > /dev/null");
    system("sudo cat /etc/proxychains4.conf > /usr/share/4n0nym1z3/data/proxychains4.txt");
    system("""sudo cat > "/etc/proxychains4.conf" << EOF
dynamic_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4 127.0.0.1 9050
socks5 127.0.0.1 9050
http 127.0.0.1 9050
EOF""");
    system("sudo systemctl restart tor");
    setdefaultproxy(PROXY_TYPE_SOCKS5, "127.0.0.1", 9050);
    socket = socksocket;
    system("sudo cat /etc/resolv.conf > /usr/share/4n0nym1z3/data/resolv.txt");
    system("""sudo cat > "/etc/resolv.conf" << EOF
generated by 4n0nym1z3
nameserver 84.200.69.80
nameserver 84.200.70.40
nameserver 91.239.100.100
nameserver 89.233.43.71
EOF""");
# End Section Function Start Ip Changer With Proxy Chains

# Start Section Function Start Mac Changer
def StartMacChanger():
    if path.isdir("/usr/share/4n0nym1z3/data/mac_addresses") == False:
    	system("sudo mkdir /usr/share/4n0nym1z3/data/mac_addresses");
    system("sudo ip -o link show | awk -F': ' '{print $2}' > /usr/share/4n0nym1z3/data/mac_addresses.txt");
    mac_addresses = open("/usr/share/4n0nym1z3/data/mac_addresses.txt", "r");
    for mac_addr in mac_addresses.read().split():
        system(f"sudo cat /sys/class/net/{mac_addr}/address > /usr/share/4n0nym1z3/data/mac_addresses/{mac_addr}.txt");
        for i in range(100):
            mac_addressesFile = open(f"/usr/share/4n0nym1z3/data/mac_addresses/{mac_addr}.txt", "r");
            mac_addresses_system = open(f"/sys/class/net/{mac_addr}/address", "r");
            if mac_addressesFile.read() == mac_addresses_system.read():
                mac_address_created = ":".join([('0'+hex(randint(0,256))[2:])[-2:].upper() for _ in range(6)]);
                system(f"sudo ip link set {mac_addr} down");
                system(f"sudo ip link set {mac_addr} address {mac_address_created}");
                system(f"sudo ip link set {mac_addr} up");
            else:
                break;
    # mac_addresses.close();
    # mac_addressesFile.close();
    # mac_addresses_system.close();
# End Section Function Start Mac Changer

# Start Section Function Start Timezone Changer
def StartTimezoneChanger():
    system("sudo timedatectl show | grep Timezone | sed 's/Timezone=//g' > /usr/share/4n0nym1z3/data/timezone.txt");
    system("sudo timedatectl set-timezone UTC");
# End Section Function Start Timezone Changer

# Start Section Function Start Hostname Changer
def StartHostnameChanger():
    system("sudo cat /etc/hostname > /usr/share/4n0nym1z3/data/hostname.txt");
    hostnames = ["Windows10-Enterprise", "Windows10-Pro", "Windows10-Enterprise-LTSC", "Windows8.1O-EM", "Windows8-Enterprise", "Windows8.1-Pro", "Windows7-Professional", "Windows7-Enterprise", "Windows7-Ultimate", "Windows-Vista-Business", "WindowsXP-Professional", "macOS11", "OSX10.11", "MacBook-Air", "MacBook", "MacBook-Pro", "macOS10.0", "macOS12", "macOS13", "macOS14"];
    random_number = randrange(0, 19);
    hostname_text = hostnames[random_number];
    system(f"sudo echo {hostname_text} > /etc/hostname");
# End Section Function Start Hostname Changer

# Start Section Function Start Browser Anonymization
def StartBrowserAnonymization():
    system("""sudo cat > "/etc/firefox-esr/firefox-esr.js" << EOF
pref("privacy.firstparty.isolate", true);
pref("privacy.resistFİngerprinting", true);
pref("privacy.trackingprotection.fingerprinting.enabled", true);
pref("privacy.trackingprotection.cryptomining.enabled", true);
pref("privacy.trackingprotection.enabled", true);
pref("browser.send_pings", false);
pref("browser.urlbar.spectulativeConnect.enabled", false);
EOF""")
# End Section Function Start Browser Anonymization

# Start Section Function Start Cold Boot
def StartColdBoot():
    system("""sudo swapoff -a
swapon -a
echo 1024 > /proc/sys/vm/min_free_kbytes
echo 3 > /proc/sys/vm/drop_caches
echo 1 > /proc/sys/vm/oom_kill_allocating_task
echo 1 > /proc/sys/vm/overcommit_memory
echo 0 > /proc/sys/vm/oom_dump_tasks""");
# End Section Function Start Cold Boot

# Start Section Function Start Log Killer
def StartLogKiller():
    system("sudo find / -iname '*.log' -type f -exec sudo rm -r {} \;");
    system("sudo find / -iname '*.log.*' -type f -exec sudo rm -r {} \;");
    system("sudo find / -iname '*.logs' -type f -exec sudo rm -r {} \;");
    system("sudo find / -iname '*.logs.*' -type f -exec sudo rm -r {} \;");
    system("sudo find / -iname '*history' -type f -exec sudo rm -r {} \;");
# End Section Function Start Log Killer

# Start Section Function Start Auto Tor Ip Changer
def StartAutoTorIpChanger():
    print("Started Ip Changer");
    while True:
        sleep(30);
        system("sudo systemctl reload tor");
        print("Ip Changed");
# End Section Function Start Auto Tor Ip Changer

# Start Section Function Start Anti Mitm
def StartAntiMitm():
    print("Started Anti Mitm");
    def process(packet):
        if packet.haslayer(ARP):
            if packet[ARP].op == 2:
                try:                
                    real_mac = srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst=packet[ARP].psrc), timeout=3, verbose=False)[0][0][1].hwsrc;
                    response_mac = packet[ARP].hwsrc;
                    if real_mac != response_mac:
                        os.system("iptables -A INPUT -m mac --mac-source " + response_mac + " -j DROP");
                except IndexError:
                    pass;
    sniff(store=False, prn=process);
# End Section Function Start Anti Mitm

# Start Section Function Start Noise Traffic Generator
def StartNoiseTrafficGenerator():
    config_json_read = load(open("/usr/share/4n0nym1z3/config.json", "r"));
    print("Started Noise Traffic Generator");
    while True:
        random_url = choice(config_json_read["main_urls"]);
        random_user_agent = choice(config_json_read["user_agents"]);
        get_post = randrange(0, 2);
        try:
            if get_post == 0:
                get(url=random_url, headers={"user-agent": random_user_agent}, timeout=2);
                print(f"GET-request : {random_url}");
            elif get_post == 1:
                post(url=random_url, headers={"user-agent": random_user_agent}, timeout=2);
                print(f"POST-request : {random_url}");
        except exceptions.HTTPError:
            pass;
        except exceptions.ReadTimeout:
            pass;
        except exceptions.ConnectionError:
            pass;
        except exceptions.RequestException:
            pass;
# End Section Function Start Noise Traffic Generator
######################################## End Section Start Functions

######################################## Start Section Stop Functions
# Start Section Function Stop Ip Changer With Tor
def StopIpChangerWithTor():
    system("sudo iptables -F");
    system("sudo iptables -X");
    system("sudo iptables -t nat -F");
    system("sudo iptables -t nat -X");
    system("sudo iptables -P INPUT ACCEPT");
    system("sudo iptables -P FORWARD ACCEPT");
    system("sudo iptables -P OUTPUT ACCEPT");
    if path.isfile("/usr/share/4n0nym1z3/data/iptables.txt") == True:
        system("sudo iptables-restore /usr/share/4n0nym1z3/data/iptables.txt");
        system("sudo rm -r /usr/share/4n0nym1z3/data/iptables.txt");
    system("sudo systemctl --system daemon-reload");
    system("sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 > /dev/null");
    system("sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=0 > /dev/null");
    system("sudo systemctl stop tor");
    if path.isfile("/usr/share/4n0nym1z3/data/torrc.txt") == True:
        system("sudo cat /usr/share/4n0nym1z3/data/torrc.txt > /etc/tor/torrc");
        system("sudo rm -r /usr/share/4n0nym1z3/data/torrc.txt");
    system("sudo cat /usr/share/4n0nym1z3/data/resolv.txt > /etc/resolv.conf");
    system("sudo rm -r /usr/share/4n0nym1z3/data/resolv.txt");
    setdefaultproxy(None);
    socket = socksocket;
    if path.isfile("/usr/share/4n0nym1z3/data/proxychains4.txt") == True:
        system("sudo cat /usr/share/4n0nym1z3/data/proxychains4.txt > /etc/proxychains4.conf");
        system("sudo rm -r /usr/share/4n0nym1z3/data/proxychains4.txt");
# End Section Function Stop Ip Changer With Tor

# Start Section Function Stop Mac Changer
def StopMacChanger():
    mac_addresses = open("/usr/share/4n0nym1z3/data/mac_addresses.txt", "r");
    for mac_addr in mac_addresses.read().split():
        mac_address_created = open(f"/usr/share/4n0nym1z3/data/mac_addresses/{mac_addr}.txt", "r");
        system(f"sudo ip link set {mac_addr} down");
        system(f"sudo ip link set {mac_addr} address {mac_address_created.read()}");
        system(f"sudo ip link set {mac_addr} up");
    system("sudo rm -r /usr/share/4n0nym1z3/data/mac_addresses.txt");
    system("sudo rm -r /usr/share/4n0nym1z3/data/mac_addresses");
    # mac_addresses.close();
    # mac_address_created.close();
# End Section Function Stop Mac Changer

# Start Section Function Stop Timezone Changer
def StopTimezoneChanger():
    time_zone = open('/usr/share/4n0nym1z3/data/timezone.txt', 'r');
    system(f"sudo timedatectl set-timezone {time_zone.read()}");
    system("sudo rm -r /usr/share/4n0nym1z3/data/timezone.txt");
    # time_zone.close();
# End Section Function Stop Timezone Changer

# Start Section Function Stop Hostname Changer
def StopHostnameChanger():
    system("sudo cat /usr/share/4n0nym1z3/data/hostname.txt > /etc/hostname");
    system("sudo rm -r /usr/share/4n0nym1z3/data/hostname.txt");
# End Section Function Stop Hostname Changer
######################################## End Section Stop Functions
############################################################################################### End Section Functions

############################################################################################### Start Section Main
try:
    if path.isdir("/usr/share/4n0nym1z3/data") == False:
        system("sudo mkdir /usr/share/4n0nym1z3/data");
    if path.isfile("/usr/share/4n0nym1z3/data/status.txt") == False:
        system("sudo echo 0 > /usr/share/4n0nym1z3/data/status.txt");

    print("note : after executing the command 'start or stop', killed apps and clear cache");
    print(help_command);
    status = open("/usr/share/4n0nym1z3/data/status.txt", "r");
    
    while True:
        input_4n0nym1z3 = input(r"""
 _  _          ___                        _     _____
| || |  _ __  / _ \ _ __  _   _ _ __ ___ / |___|___ /
| || |_| '_ \| | | | '_ \| | | | '_ ` _ \| |_  / |_ \
|__   _| | | | |_| | | | | |_| | | | | | | |/ / ___) |
   |_| |_| |_|\___/|_| |_|\__, |_| |_| |_|_/___|____/
                          |___/

4n0nym1z3 > """);

        if (input_4n0nym1z3 == "swt"):
            system("sudo clear");
            status.seek(0);
            if int(status.read()) == 0:
                StartKillAppsAndClearCache();
                
                StartIpChangerWithTor();

                StartMacChanger();

                StartTimezoneChanger();

                StartHostnameChanger();

                StartBrowserAnonymization();

                StartColdBoot();

                StartLogKiller();

                system("sudo echo 1 > /usr/share/4n0nym1z3/data/status.txt");
                system("sudo clear");
                print("4n0nym1z3 successfully enabled");
            else:
                print("4n0nym1z3 is already enabled");
        elif (input_4n0nym1z3 == "swp"):
            system("sudo clear");
            status.seek(0);
            if int(status.read()) == 0:
                StartKillAppsAndClearCache();
                
                StartIpChangerWithProxyChains();

                StartMacChanger();

                StartTimezoneChanger();

                StartHostnameChanger();

                StartBrowserAnonymization();

                StartColdBoot();

                StartLogKiller();

                system("sudo echo 1 > /usr/share/4n0nym1z3/data/status.txt");
                system("sudo clear");
                print("4n0nym1z3 successfully enabled");
            else:
                print("4n0nym1z3 is already enabled");
        elif (input_4n0nym1z3 == "stop"):
            system("sudo clear");
            status.seek(0);
            if int(status.read()) == 1:
                StartKillAppsAndClearCache();
                
                StopIpChangerWithTor();
                
                StopMacChanger();
                
                StopTimezoneChanger();
                
                StopHostnameChanger();

                StartLogKiller();

                system("sudo echo 0 > /usr/share/4n0nym1z3/data/status.txt");
                system("sudo clear");
                print("4n0nym1z3 successfully disabled");
            else:
                print("4n0nym1z3 is already disabled");
        elif (input_4n0nym1z3 == "ti"):
            system("sudo clear");
            StartAutoTorIpChanger();
        elif (input_4n0nym1z3 == "am"):
            system("sudo clear");
            StartAntiMitm();
        elif (input_4n0nym1z3 == "n"):
            system("sudo clear");
            StartNoiseTrafficGenerator();
        elif (input_4n0nym1z3 == "tiam"):
            system("sudo clear");
            StartAutoTorIpChanger = Process(target=StartAutoTorIpChanger);
            StartAntiMitm = Process(target=StartAntiMitm);
            
            StartAutoTorIpChanger.start();
            StartAntiMitm.start();
            
            StartAutoTorIpChanger.join();
            StartAntiMitm.join();
        elif (input_4n0nym1z3 == "tiamn"):
            system("sudo clear");
            StartAutoTorIpChanger = Process(target=StartAutoTorIpChanger);
            StartAntiMitm = Process(target=StartAntiMitm);
            StartNoiseTrafficGenerator = Process(target=StartNoiseTrafficGenerator);
                        
            StartAutoTorIpChanger.start();
            StartAntiMitm.start();
            StartNoiseTrafficGenerator.start();
            
            StartAutoTorIpChanger.join();
            StartAntiMitm.join();
            StartNoiseTrafficGenerator.join();
        elif (input_4n0nym1z3 == "0"):
            system("sudo clear");
            StartKillAppsAndClearCache();
            system("sudo clear");
        elif (input_4n0nym1z3 == "1"):
            system("sudo clear");
            StartLogKiller();
            system("sudo clear");
        elif (input_4n0nym1z3 == "status"):
            system("sudo clear");
            status.seek(0);
            if int(status.read()) == 1:
                print("4n0nym1z3 is already enabled");
            else:
                print("4n0nym1z3 is already disabled");
        elif (input_4n0nym1z3 == "help"):
            system("sudo clear");
            print(help_command);
        elif (input_4n0nym1z3 == "clear"):
            system("sudo clear");
        elif (input_4n0nym1z3 == "install"):
            system("sudo clear");
            system("""sudo apt update -y &&
sudo apt install python3 -y &&
sudo apt install bleachbit -y &&
sudo apt install iproute2 -y &&
sudo apt install sed -y &&
sudo apt install grep -y &&
sudo apt install findutils -y &&
sudo apt install iptables -y &&
sudo apt install tor -y &&
sudo apt install proxychains4 -y &&
sudo pip install random2 &&
sudo pip install simplejson &&
sudo pip install requests &&
sudo pip install socks &&
sudo pip install sockets &&
sudo pip install scapy &&
sudo pip install multiprocessing""");
        elif (input_4n0nym1z3 == "exit"):
            break;
        else:
            system("sudo clear");
            print(f"ERR `{input_4n0nym1z3}` is an unknown command");
        # status.close();
except Exception as e:
    print(e);
############################################################################################### End Section Main
